POST http://localhost:3337/users
content-type: application/json

{
    "name": "George",
    "email": "george@george.com",
    "password": "123456788",
    "confirm_password": "123456788"
}

######

GET http://localhost:3337/users


###

GET http://localhost:3337/users/7


###
PUT http://localhost:3337/users/7
content-type: application/json

{
    "name": "Bradley",
    "email": "bradley@bradley",
    "password": "123456788",
    "confirm_password": "123456788"
}

###

DELETE  http://localhost:3337/users/6

###

POST http://localhost:3337/thoughts
content-type: application/json

{
    "title": "Pensamento 01",
    "description": "Vai dar certo!"
}

###

GET http://localhost:3337/thoughts

###

GET http://localhost:3337/thoughts/6

###

PUT http://localhost:3337/thoughts/6
content-type: application/json

{
    "title": "Pensamento 02",
    "description": "Eh, mais ou menos"
}

###

DELETE  http://localhost:3337/thoughts/6